import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | LearningOrbit",
  description: "Read the terms and conditions for using LearningOrbit's AI-powered exam preparation platform.",
};

export default function TermsPage() {
  const lastUpdated = "August 20, 2026";

  const sections = [
    {
      title: "Acceptance of Terms",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M9 11l3 3L22 4" /><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11" />
        </svg>
      ),
      content: "By accessing or using LearningOrbit (learningorbit.in), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the platform. These terms apply to all visitors, users, and registered accounts.",
    },
    {
      title: "Eligibility",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2" /><circle cx="12" cy="7" r="4" />
        </svg>
      ),
      content: "LearningOrbit is open to all students preparing for Indian competitive exams including JEE, NEET, GATE, UPSC, CAT, CA, and CLAT. You must be at least 13 years of age to create an account. If you are under 18, you should have parental consent before registering.",
    },
    {
      title: "Account Responsibilities",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <rect x="3" y="11" width="18" height="11" rx="2" ry="2" /><path d="M7 11V7a5 5 0 0110 0v4" />
        </svg>
      ),
      content: "You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. LearningOrbit is not liable for any loss resulting from unauthorised access to your account. Please notify us immediately at tutorai.official.dev@gmail.com if you suspect any unauthorised use.",
    },
    {
      title: "Use of the Platform",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <circle cx="12" cy="12" r="10" /><line x1="2" y1="12" x2="22" y2="12" />
          <path d="M12 2a15.3 15.3 0 014 10 15.3 15.3 0 01-4 10 15.3 15.3 0 01-4-10 15.3 15.3 0 014-10z" />
        </svg>
      ),
      content: "LearningOrbit is provided for personal, non-commercial educational use only. You may not reproduce, redistribute, scrape, or commercially exploit any content generated by the platform. AI-generated study roadmaps are personalised for your use and may not be resold or published.",
    },
    {
      title: "AI-Generated Content",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
        </svg>
      ),
      content: "Study roadmaps, topic suggestions, and learning plans are generated by AI and are intended as study guidance only. LearningOrbit does not guarantee that AI-generated content is complete, accurate, or up-to-date with the latest exam syllabus. Always verify with official exam notifications and authoritative resources. LearningOrbit is not liable for exam outcomes.",
    },
    {
      title: "Intellectual Property",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <circle cx="12" cy="12" r="10" /><path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83M16.62 12l-5.74 9.94" />
        </svg>
      ),
      content: "The LearningOrbit name, logo, and platform design are the intellectual property of LearningOrbit. The underlying AI models are provided by third parties under their respective licenses. You retain ownership of any personal data you input, but grant LearningOrbit a limited license to process it to provide the service.",
    },
    {
      title: "Prohibited Conduct",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <circle cx="12" cy="12" r="10" /><line x1="4.93" y1="4.93" x2="19.07" y2="19.07" />
        </svg>
      ),
      content: "You may not use the platform to: attempt to reverse-engineer or extract AI models; submit automated or bot-driven requests; upload harmful, illegal, or deceptive content; impersonate another user or person; or attempt to disrupt the service or infrastructure of LearningOrbit. Violations may result in immediate account termination.",
    },
    {
      title: "Termination",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <polyline points="9 10 4 15 9 20" /><path d="M20 4v7a4 4 0 01-4 4H4" />
        </svg>
      ),
      content: "You may delete your account at any time by contacting us. LearningOrbit reserves the right to suspend or terminate any account that violates these terms, without prior notice. Upon termination, your access to the platform will cease and your data will be deleted per our Privacy Policy.",
    },
    {
      title: "Limitation of Liability",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
        </svg>
      ),
      content: "LearningOrbit is provided 'as is' without warranties of any kind. To the maximum extent permitted by applicable law, LearningOrbit shall not be liable for any indirect, incidental, or consequential damages arising from your use of the platform, including but not limited to reliance on AI-generated content for exam preparation.",
    },
    {
      title: "Governing Law",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M3 6l9-4 9 4v6c0 5.55-3.84 10.74-9 12-5.16-1.26-9-6.45-9-12V6z" />
        </svg>
      ),
      content: "These Terms of Service are governed by the laws of India. Any disputes arising from the use of LearningOrbit shall be subject to the exclusive jurisdiction of the courts located in West Bengal, India.",
    },
    {
      title: "Changes to Terms",
      icon: (
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7" />
          <path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z" />
        </svg>
      ),
      content: "We may update these Terms at any time. Significant changes will be communicated via email or an in-app notice. Your continued use of LearningOrbit after changes are posted constitutes acceptance of the updated terms.",
    },
  ];

  return (
    <div style={{ minHeight: "100vh", backgroundColor: "#0F172A", color: "#F8FAFC" }}>
      {/* Header */}
      <div
        style={{
          background: "linear-gradient(135deg, #0F172A 0%, #1B1340 50%, #0F172A 100%)",
          borderBottom: "1px solid rgba(99,102,241,0.15)",
          padding: "60px 24px 48px",
          textAlign: "center",
          position: "relative",
          overflow: "hidden",
        }}
      >
        <div
          style={{
            position: "absolute",
            top: "50%",
            left: "50%",
            transform: "translate(-50%, -50%)",
            width: "320px",
            height: "120px",
            border: "1px solid rgba(99,102,241,0.08)",
            borderRadius: "50%",
            pointerEvents: "none",
          }}
        />
        <div style={{ position: "relative", zIndex: 1 }}>
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              gap: "8px",
              background: "rgba(99,102,241,0.1)",
              border: "1px solid rgba(99,102,241,0.25)",
              borderRadius: "20px",
              padding: "6px 16px",
              marginBottom: "20px",
            }}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#A78BFA" strokeWidth="2">
              <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
              <polyline points="14 2 14 8 20 8" />
            </svg>
            <span style={{ color: "#A78BFA", fontSize: "13px", fontWeight: 500 }}>Legal</span>
          </div>
          <h1
            style={{
              fontSize: "clamp(28px, 5vw, 42px)",
              fontWeight: 700,
              margin: "0 0 12px",
              background: "linear-gradient(135deg, #F8FAFC 0%, #A78BFA 100%)",
              WebkitBackgroundClip: "text",
              WebkitTextFillColor: "transparent",
              backgroundClip: "text",
            }}
          >
            Terms of Service
          </h1>
          <p style={{ color: "#64748B", fontSize: "14px", margin: 0 }}>
            Last updated: {lastUpdated}
          </p>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth: "800px", margin: "0 auto", padding: "48px 24px 80px" }}>
        {/* Intro */}
        <div
          style={{
            background: "rgba(99,102,241,0.06)",
            border: "1px solid rgba(99,102,241,0.15)",
            borderRadius: "12px",
            padding: "24px",
            marginBottom: "48px",
          }}
        >
          <p style={{ color: "#94A3B8", lineHeight: 1.7, margin: 0, fontSize: "15px" }}>
            Please read these Terms of Service carefully before using LearningOrbit. These terms govern your access to and use of our AI-powered exam preparation platform.
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: "flex", flexDirection: "column", gap: "4px" }}>
          {sections.map((section, idx) => (
            <div
              key={idx}
              style={{
                background: "rgba(255,255,255,0.02)",
                border: "1px solid rgba(255,255,255,0.06)",
                borderRadius: "12px",
                padding: "24px",
                marginBottom: "8px",
              }}
            >
              <div style={{ display: "flex", alignItems: "flex-start", gap: "14px" }}>
                <div
                  style={{
                    width: "36px",
                    height: "36px",
                    borderRadius: "10px",
                    background: "rgba(99,102,241,0.15)",
                    border: "1px solid rgba(99,102,241,0.2)",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "#A78BFA",
                    flexShrink: 0,
                    marginTop: "2px",
                  }}
                >
                  {section.icon}
                </div>
                <div style={{ flex: 1 }}>
                  <h2 style={{ fontSize: "17px", fontWeight: 600, margin: "0 0 10px", color: "#F8FAFC" }}>
                    {section.title}
                  </h2>
                  <p style={{ color: "#94A3B8", lineHeight: 1.7, margin: 0, fontSize: "14px" }}>
                    {section.content}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Contact CTA */}
        <div
          style={{
            background: "linear-gradient(135deg, rgba(99,102,241,0.1), rgba(139,92,246,0.1))",
            border: "1px solid rgba(99,102,241,0.2)",
            borderRadius: "16px",
            padding: "32px 24px",
            textAlign: "center",
            marginTop: "40px",
          }}
        >
          <p style={{ color: "#94A3B8", fontSize: "15px", margin: "0 0 8px" }}>
            Questions about these terms?
          </p>
          <a
            href="mailto:tutorai.official.dev@gmail.com"
            style={{ color: "#A78BFA", fontSize: "16px", fontWeight: 600, textDecoration: "none" }}
          >
            tutorai.official.dev@gmail.com
          </a>
        </div>
      </div>
    </div>
  );
}